name: activite1
description: "Application de gestion des rédacteurs pour Magazine Info"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/magazineInfo.jpeg
    - assets/images/presse.jpeg
    - assets/images/mode.jpeg

